name: Publish & Release
on:
  push:
    branches: [main]

jobs:
  publish-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Publish AvmWinNode
        run: |
          cd AvmWinNode
          dotnet publish -o ..\publish

      - name: Publish NodeService
        run: |
          cd NodeService
          dotnet publish -o ..\publish\Services

      - name: Publish RetiService
        run: |
          cd RetiService
          dotnet publish -o ..\publish\Services

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Build webui
        run: |
          cd webui
          pnpm install
          pnpm build

      - name: Create Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: ./AvmWinNode.iss

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: v1.1.1
          artifacts: "Output\\AvmWinNode_Setup.exe"
