name: Publish & Release
on:
  push:
    branches: [main]

jobs:
  webui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Build webui
        run: |
          cd webui
          pnpm install
          pnpm build
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webui
          path: "publish/wwwroot"
          retention-days: 1

  debian-package:
    runs-on: ubuntu-latest
    needs: webui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Publish FUNC
        run: |
          cd FUNC
          dotnet publish -o ../publish
          cd ..

      - name: Download webui Artifact
        uses: actions/download-artifact@v4
        with:
          name: webui
          path: "publish/wwwroot"

      - name: Create Package
        run: ./create-package.sh

      - name: Upload deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: "Output/*.deb"
          retention-days: 1

  windows-setup:
    runs-on: windows-latest
    needs: webui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Publish FUNC
        run: |
          cd FUNC
          dotnet publish -o ..\publish
          cd ..

      - name: Publish NodeService
        run: |
          cd NodeService
          dotnet publish -o ..\publish\Services
          cd ..

      - name: Publish RetiService
        run: |
          cd RetiService
          dotnet publish -o ..\publish\Services
          cd ..

      - name: Download webui Artifact
        uses: actions/download-artifact@v4
        with:
          name: webui
          path: "publish/wwwroot"

      - name: Create Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: ./FUNC.iss

      - name: Upload win Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-setup
          path: "Output"
          retention-days: 1

  create-release:
    runs-on: ubuntu-latest
    needs: [debian-package, windows-setup]
    steps:
      - name: Download deb Artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: "Output"

      - name: Download win Artifact
        uses: actions/download-artifact@v4
        with:
          name: win-setup
          path: "Output"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: v2.0.5
          artifacts: "Output/*"
